name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: none

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Output Run ID
        run: echo ${{ github.run_id }}

    - name: Output Run Number
        run: echo ${{ github.run_number }}

    - name: Checkout the code
      uses: actions/checkout@v2

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag reveal-etl:$(date +%s)

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: revealprecision
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: reveal-precision/reveal-etl:v${{ github.run_number }}