name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: none

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Build the Docker image
      uses: actions/checkout@v2
      run: docker build . --file Dockerfile --tag reveal-etl:$(date +%s)

    - name: Push the Docker image
      uses: docker/build-push-action@v1
      with:
        username: revealprecision
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: revealprecision/reveal-etl
        push: ${{ GitHub.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
