name: Pylint

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint redis anybadge
    - name: Analysing the code with pylint
      run: |
        mkdir .pylint
        pylint --disable=C0301 --fail-under=9.25 --output-format=text . `ls -R|grep .py$|xargs` | tee ./.pylint/pylint.log
        PYLINT_SCORE=$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' ./.pylint/pylint.log)
        anybadge --label=Pylint --file=.pylint/pylint.svg --value=$PYLINT_SCORE 7=red 8.5=orange 9=yellow 9.25=green
        echo "Pylint score is $PYLINT_SCORE"
    - name: Archive the badge
      uses: actions/upload-artifact@v2
      with:
        name: pylint-badge
        path: .pylint/pylint.svg
